### ISSUE TITLE
.NetStandard - Interception works 1 level, but not 2.

### ISSUE THREAD

**Issue by scovel** [unitycontainer/interception#14]
**Interception at one level works...**
ControllerA(IBusinessServiceA businessService)

BusinessService is injected, I see WillExecute, GetRequiredInterfaces, Invoke all run 

**Interception 2-deep does not work...**
ControllerB(IBusinessServiceB businessService)
BusinessServiceB(IDal dal)

I see Will Execute, GetRequiredInterfaces for Dal, and I see the DAL constructor fire, I see the BusinessServiceB constructor fire.  WillExecute and GetRequiredInterfaces fire, then I get an exception.

`container.RegisterType<IBusinessServiceA, BusinessServiceA>(new Interceptor<InterfaceInterceptor>(), new InterceptionBehavior<MyInterceptionBehaviorA>());`
 ` container.RegisterType<IBusinessServiceB, BusinessServiceB>(new Interceptor<InterfaceInterceptor>(), new InterceptionBehavior<MyInterceptionBehaviorA>());`
`container.RegisterType<IDal, Dal>(new Interceptor<InterfaceInterceptor>(), new InterceptionBehavior<MyInterceptionBehaviorB>());`

Works fine with normal registration.

`container.RegisterType<IBusinessServiceA, BusinessServiceA>();`
`container.RegisterType<IBusinessServiceB, BusinessServiceB>();`
`container.RegisterType<IDal, Dal>();`

Here's the exception...

warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://localhost:53382/'. Binding to endpoints defined in UseKestrel() instead.
Hosting environment: Development
Content root path: c:\users\scovel\Source\Repos\TestUnity\TestUnity
Now listening on: http://127.0.0.1:8088
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLDAT7258BVT", Request id "0HLDAT7258BVT:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Unable to resolve service for type 'TestUnity.Implementations.IBusinessServiceB' while attempting to activ
ate 'TestUnity.Controllers.ValuesControllerB'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParamete
rRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controll
erContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(Con
trollerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()

**Comment by scovel** [comment]
Additional information:  Getting the following exception when running with a debug unity.interception:

System.InvalidOperationException: 'You cannot have more than one dynamic module in each dynamic assembly in this version of the runtime.'

The exception is in 

`public partial class InterfaceInterceptorClassGenerator
`    {
`        private static ModuleBuilder GetModuleBuilder()
`        {
`
`            string moduleName = Guid.NewGuid().ToString("N");
`
`#if DEBUG_SAVE_GENERATED_ASSEMBLY
`
`            return AssemblyBuilder.DefineDynamicModule(moduleName, moduleName + ".dll", true);
`
`#else
`
`            return AssemblyBuilder.DefineDynamicModule(moduleName);  <--exception here
`
`#endif
`        }
`    }

**Comment by witskeeper** [comment]
var container = new Unity.UnityContainer();
            container.AddNewExtension<Unity.Interception.ContainerIntegration.Interception>();
            container.RegisterType<FakeInterceptionBehavior>();

            container.RegisterType<IFakeService, FakeServcice>().Configure<Unity.Interception.ContainerIntegration.Interception>().SetInterceptorFor<IFakeService>(new InterfaceInterceptor());
            container.RegisterType<IFakeService2, FakeServcice2>().Configure<Unity.Interception.ContainerIntegration.Interception>().SetInterceptorFor<IFakeService2>(new InterfaceInterceptor());


            var service2 = container.Resolve<IFakeService2>();
            var service1 = container.Resolve<IFakeService>();
//got exception here

**Comment by staal-it** [comment]
Any news on this one?

**Comment by scovel** [comment]
I gave up and moved to Grace.  https://github.com/ipjohnson/Grace.  Working great.

**Comment by ENikS** [comment]
Just submit a pull request and you are a contributor.

**Comment by hecflores** [comment]
I am not able to make a Pull Request because I need to push a Branch that I can do a Pull Request from. 

I thought maybe you guys have a branch naming policy enabled so I tried two different branch names to do a Pull Request from and I get the same error.

> Checked out issue/hectorhpflores72/14
> Pushing issue/hectorhpflores72/14
> Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
> unable to access 'https://github.com/unitycontainer/interception.git/': The requested URL returned error: 403
> Pushing to https://github.com/unitycontainer/interception.git

> Checked out master
> Checked out master-issus-14
> Pushing master-issus-14
> Error encountered while pushing branch to the remote repository: Git failed with a fatal error.
> unable to access 'https://github.com/unitycontainer/interception.git/': The requested URL returned error: 403
> Pushing to https://github.com/unitycontainer/interception.git

**Comment by ENikS** [comment]
Did you fork the repository or you are trying to push to the origin?

**Comment by hecflores** [comment]
I created a new branch off of the latest. Trying to push the branch so that
I can open a PR off that branch for review... But when I push the branch I
get permission errors.

**Comment by yfital** [comment]
Hey,

The solution was only semi and was fixed only for interface interception (not for virtual).
I've already cloned and fix the bug for all interception types but I'm getting 403 (same as hecflores), I presume you need to open permissions for me? (branched off latest).

My solution is to move the module builder itself outside of the partial and have it receive the assembly builder, after that, it holds a concurrent dictionary which generates the dynamic module.

Let me know how I can push and i'll open the PR,
Thanks.

**Comment by ENikS** [comment]
Are you getting 403 when creating pull request? You will not be able to write to repository directly.

**Comment by yfital** [comment]
No, I've created a branch from the latest and wanted to push it.
Do i have to fork?

**Comment by ENikS** [comment]
You do need a fork to follow the GitHub workflow.

**Comment by yfital** [comment]
PR opened:
https://github.com/unitycontainer/interception/pull/25

**Comment by quintindk** [comment]
thanks for this fix, works a charm.
